services:
  app:
    build: .
    container_name: jam_and_flow_api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - jamandflows-network

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - jamandflows-network

volumes:
  postgres_data:

networks:
  jamandflows-network:
    external: true
